app:
  name: "Turtle"
  version: "1.0.0"
  upload:
    dir: /tmp

spring:
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/emsdb
    username: ems
    password: example
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

logging:
  level:
    '[org.springframework.security]': DEBUG
    '[com.fwai.turtle]': DEBUG
    '[org.springframework.web]': DEBUG

token:
  signing:
    secretKey: "NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3Nl"
    issuer: "fwai"
  access:
    expiration: 900
  refresh:
    expiration: 604800