-- ================================================
-- Turtle HR Module - Employee Application System
-- 员工入职申请系统数据库迁移
-- Version: 2025.09.07.001
-- Author: Claude Code
-- ================================================

-- 1. 扩展employees表，添加社保公积金等字段
-- Extend employees table with social security and provident fund fields
ALTER TABLE employees 
ADD COLUMN social_security_number VARCHAR(50),
ADD COLUMN provident_fund_number VARCHAR(50),
ADD COLUMN bank_account VARCHAR(100),
ADD COLUMN bank_name VARCHAR(100);

-- 为新字段添加注释
COMMENT ON COLUMN employees.social_security_number IS '社保号';
COMMENT ON COLUMN employees.provident_fund_number IS '公积金账号';
COMMENT ON COLUMN employees.bank_account IS '银行账号';
COMMENT ON COLUMN employees.bank_name IS '开户银行';

-- 2. 创建员工入职申请表
-- Create employee_applications table
CREATE TABLE employee_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'SUBMITTED',
    
    -- 申请人基本信息 Basic Information
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    birthday DATE,
    gender VARCHAR(10),
    ethnicity VARCHAR(50),
    id_type VARCHAR(20),
    id_number VARCHAR(50) NOT NULL,
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    
    -- 社保公积金信息 Social Security & Provident Fund
    social_security_number VARCHAR(50),
    provident_fund_number VARCHAR(50),
    bank_account VARCHAR(100),
    bank_name VARCHAR(100),
    
    -- 求职信息 Job Application Info
    desired_position VARCHAR(100),
    expected_salary VARCHAR(50),
    preferred_contract_type VARCHAR(20),
    self_introduction TEXT,
    work_experience TEXT,
    education_background TEXT,
    certifications TEXT,
    
    -- 关联用户 Associated Users
    applicant_user_id BIGINT NOT NULL,
    reviewer_user_id BIGINT,
    
    -- 审核信息 Review Information
    review_comments TEXT,
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    
    -- 时间戳 Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- 外键约束 Foreign Key Constraints
    CONSTRAINT fk_employee_app_applicant FOREIGN KEY (applicant_user_id) REFERENCES users(id),
    CONSTRAINT fk_employee_app_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(id)
);

-- 为employee_applications表添加注释
COMMENT ON TABLE employee_applications IS '员工入职申请表';
COMMENT ON COLUMN employee_applications.id IS '申请ID';
COMMENT ON COLUMN employee_applications.status IS '申请状态: SUBMITTED, UNDER_REVIEW, APPROVED, REJECTED, SUPPLEMENTARY_REQUIRED';
COMMENT ON COLUMN employee_applications.name IS '申请人姓名';
COMMENT ON COLUMN employee_applications.email IS '申请人邮箱';
COMMENT ON COLUMN employee_applications.phone IS '申请人电话';
COMMENT ON COLUMN employee_applications.birthday IS '生日';
COMMENT ON COLUMN employee_applications.gender IS '性别';
COMMENT ON COLUMN employee_applications.ethnicity IS '民族';
COMMENT ON COLUMN employee_applications.id_type IS '证件类型';
COMMENT ON COLUMN employee_applications.id_number IS '证件号码';
COMMENT ON COLUMN employee_applications.emergency_contact_name IS '紧急联系人姓名';
COMMENT ON COLUMN employee_applications.emergency_contact_phone IS '紧急联系人电话';
COMMENT ON COLUMN employee_applications.social_security_number IS '社保号';
COMMENT ON COLUMN employee_applications.provident_fund_number IS '公积金账号';
COMMENT ON COLUMN employee_applications.bank_account IS '银行账号';
COMMENT ON COLUMN employee_applications.bank_name IS '开户银行';
COMMENT ON COLUMN employee_applications.desired_position IS '期望职位';
COMMENT ON COLUMN employee_applications.expected_salary IS '期望薪资';
COMMENT ON COLUMN employee_applications.preferred_contract_type IS '期望合同类型';
COMMENT ON COLUMN employee_applications.self_introduction IS '自我介绍';
COMMENT ON COLUMN employee_applications.work_experience IS '工作经验描述';
COMMENT ON COLUMN employee_applications.education_background IS '学历背景描述';
COMMENT ON COLUMN employee_applications.certifications IS '证书信息';
COMMENT ON COLUMN employee_applications.applicant_user_id IS '申请人用户ID';
COMMENT ON COLUMN employee_applications.reviewer_user_id IS '审核人用户ID';
COMMENT ON COLUMN employee_applications.review_comments IS '审核意见';
COMMENT ON COLUMN employee_applications.submitted_at IS '提交时间';
COMMENT ON COLUMN employee_applications.reviewed_at IS '审核时间';
COMMENT ON COLUMN employee_applications.created_at IS '创建时间';
COMMENT ON COLUMN employee_applications.updated_at IS '更新时间';

-- 3. 创建索引优化查询性能
-- Create indexes for better query performance

-- 基于状态查询的索引
CREATE INDEX idx_employee_applications_status ON employee_applications(status);

-- 基于申请人的索引
CREATE INDEX idx_employee_applications_applicant ON employee_applications(applicant_user_id);

-- 基于审核人的索引  
CREATE INDEX idx_employee_applications_reviewer ON employee_applications(reviewer_user_id);

-- 基于身份证号的唯一索引
CREATE UNIQUE INDEX idx_employee_applications_id_number ON employee_applications(id_number);

-- 基于邮箱的索引
CREATE INDEX idx_employee_applications_email ON employee_applications(email);

-- 基于创建时间的索引（用于排序）
CREATE INDEX idx_employee_applications_created_at ON employee_applications(created_at DESC);

-- 基于状态和创建时间的组合索引
CREATE INDEX idx_employee_applications_status_created ON employee_applications(status, created_at DESC);

-- 4. 创建触发器自动更新updated_at字段
-- Create trigger to automatically update updated_at field
CREATE OR REPLACE FUNCTION update_employee_applications_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_employee_applications_updated_at
    BEFORE UPDATE ON employee_applications
    FOR EACH ROW
    EXECUTE FUNCTION update_employee_applications_updated_at();

-- 5. 插入一些测试数据（可选，用于开发测试）
-- Insert some test data (optional, for development testing)

-- 注意：在生产环境中应该注释掉测试数据插入部分
-- Note: Comment out test data insertion in production environment

/*
-- 为GUEST用户创建一个测试申请（假设存在ID为1的GUEST用户）
INSERT INTO employee_applications (
    name, email, phone, birthday, gender, ethnicity, 
    id_type, id_number, emergency_contact_name, emergency_contact_phone,
    desired_position, expected_salary, preferred_contract_type,
    self_introduction, applicant_user_id, status
) VALUES (
    '张三', 'zhangsan@example.com', '13800138000', '1990-01-01', 'MALE', '汉族',
    'ID_CARD', '110101199001010001', '张父', '13800138001',
    '软件工程师', '10000-15000', 'PERMANENT',
    '我是一名有5年经验的软件工程师，熟悉Java和前端开发...', 1, 'SUBMITTED'
);
*/

-- 6. 授予必要的权限
-- Grant necessary permissions
-- GRANT SELECT, INSERT, UPDATE, DELETE ON employee_applications TO turtle_app_user;
-- GRANT USAGE, SELECT ON SEQUENCE employee_applications_id_seq TO turtle_app_user;

-- ================================================
-- Migration Validation
-- 迁移验证
-- ================================================

-- 验证employees表新字段
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'employees' 
AND column_name IN ('social_security_number', 'provident_fund_number', 'bank_account', 'bank_name');

-- 验证employee_applications表创建
SELECT table_name, column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_name = 'employee_applications'
ORDER BY ordinal_position;

-- 验证索引创建
SELECT indexname, indexdef 
FROM pg_indexes 
WHERE tablename = 'employee_applications';

-- ================================================
-- End of Migration
-- ================================================