# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image:  postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ems
      POSTGRES_DB: emsdb
    networks:
      - jwt-network
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8080
    networks:
      - jwt-network

networks:
  jwt-network:
