# Use postgres/example user/password credentials
services:
  db:
    image:  postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ems
      POSTGRES_DB: emsdb
    networks:
      - jwt-network
  
networks:
  jwt-network:
