# Use postgres/example user/password credentials
services:
  db:
    image:  postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ems
      POSTGRES_DB: emsdb
    networks:
      - jwt-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - jwt-network
  
networks:
  jwt-network:

volumes:
  redis_data:
